FROM node:20-alpine

# Dossier de travail
WORKDIR /app

# Dépendances
COPY package.json package-lock.json* ./
RUN npm install

# Code
COPY . .

# Port Next
EXPOSE 3006

# Lancer Next en dev
CMD ["npm", "run", "dev"]